Add method for groups.setAnnouncement
jadolg/rocketchat_API pull request #149
Opened 2021-11-15 15:09 UTC by BenjaminBoehm

https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/groups-endpoints/setannouncement

2021-11-16 22:47 UTC, jadolg requested changes

2021-11-16 22:47 UTC, jadolg commented on rocketchat_API/APISections/groups.py
> +    def groups_set_announcement(self, room_id, announce, **kwargs):
I'd like to keep it as close to the API naming as possible as long as we don't break Python's style
```suggestion
    def groups_set_announcement(self, room_id, announcement, **kwargs):
```

2021-11-16 22:47 UTC, jadolg commented on rocketchat_API/APISections/groups.py
> +            announcement=announce,
```suggestion
            announcement=announcement,
```

2021-11-17 10:09 UTC, BenjaminBoehm commented
Then we should consider changing the `channels_set_announcement` argument as well to keeping API naming:
https://github.com/jadolg/rocketchat_API/blob/5ef7fba34f140673726d3c8bfb4ac87bc563b93c/rocketchat_API/APISections/channels.py#L176

Reference: https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/setannouncement

2021-11-17 16:53 UTC, jadolg commented
> Then we should consider changing the `channels_set_announcement` argument as well to keep API naming:
> 
> https://github.com/jadolg/rocketchat_API/blob/5ef7fba34f140673726d3c8bfb4ac87bc563b93c/rocketchat_API/APISections/channels.py#L176
> 
> Reference: https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/setannouncement

nice catch :)

2021-11-17 19:51 UTC, merged